### ISSUE TITLE
Fix the improper depth for grasping

### ISSUE THREAD

**Issue by praveenVnktsh** [Auxilio-Robotics/Stretch#28]
**Describe the bug**
Robot is not reaching desired point of interest accurately.

**Comment by AbhinavGupta121** [comment]
a) We can run graspnet and check its results.
b) We can find the centroid by cropping a patch of region and taking the median in it.

**Comment by praveenVnktsh** [comment]
Sorted. Fixed due to two bugs:
- Centroid grasp changed from mean to median
- Visual serving limit was insufficient, so it was unable to extend to max length.
